import { useThemedStyles } from '../theme/ThemeProvider';

export function useProfileScreenStyles() {
  return useThemedStyles((colors) => ({
    scroll: { paddingBottom: 28 },
    card: {
      marginTop: 14,
      borderRadius: 22,
      backgroundColor: colors.cardTint,
      borderWidth: 1,
      borderColor: colors.profileAccentBorder,
      padding: 18,
      alignItems: 'center',
      gap: 8,
    },
    avatar: {
      width: 60,
      height: 60,
      borderRadius: 18,
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.profileAccentBorder,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    avatarImg: { width: '100%', height: '100%' },
    avatarText: { fontSize: 22, fontWeight: '900', color: colors.text },
    name: { fontSize: 18, fontWeight: '900', color: colors.text },
    handle: { fontSize: 13, fontWeight: '700', color: colors.muted, marginTop: -2 },
    profileBio: {
      marginTop: 8,
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '600',
      color: colors.text,
      textAlign: 'center',
      paddingHorizontal: 8,
    },
    editProfileBtn: {
      marginTop: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: 'rgba(255, 107, 84, 0.35)',
      backgroundColor: colors.card,
    },
    editProfileBtnText: { fontSize: 14, fontWeight: '900', color: colors.coral },
    profileActionsRow: {
      marginTop: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
      flexWrap: 'wrap',
    },
    messageBtn: {
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.moss,
      backgroundColor: 'rgba(39, 174, 96, 0.08)',
      minWidth: 100,
      alignItems: 'center',
      justifyContent: 'center',
    },
    messageBtnTxt: { fontSize: 14, fontWeight: '800', color: colors.moss },
    scoreCard: {
      marginTop: 14,
      borderRadius: 22,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.card,
      padding: 18,
      gap: 6,
    },
    scoreTitle: { fontSize: 11, letterSpacing: 2.2, fontWeight: '900', color: colors.muted },
    scoreNumber: { fontSize: 44, fontWeight: '900', color: colors.text, marginTop: 4 },
    scoreTierHint: { fontSize: 13, fontWeight: '700', color: colors.muted, lineHeight: 18 },
    statsRow: { flexDirection: 'row', gap: 12, marginTop: 14 },
    stat: {
      flex: 1,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.card,
      paddingVertical: 14,
      alignItems: 'center',
      gap: 6,
    },
    statTappable: { borderColor: 'rgba(39, 174, 96, 0.35)' },
    statPressed: { opacity: 0.92 },
    statNum: { fontSize: 20, fontWeight: '900', color: colors.text },
    statLabel: {
      fontSize: 10,
      letterSpacing: 1.6,
      fontWeight: '900',
      color: colors.muted,
      textAlign: 'center',
    },
    dailyBanner: {
      marginTop: 12,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.profileAccentBorder,
      backgroundColor: colors.cardTint,
      paddingVertical: 12,
      paddingHorizontal: 16,
      alignItems: 'center',
    },
    dailyBannerText: { fontSize: 16, fontWeight: '900', color: colors.moss },
    openLeapsCta: {
      marginTop: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 14,
      paddingHorizontal: 16,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.card,
    },
    openLeapsCtaText: { fontSize: 15, fontWeight: '900', color: colors.text, flex: 1 },
  }));
}
