import * as React from 'react';
import {
  ActivityIndicator,
  FlatList,
  Platform,
  Pressable,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';

import { useTheme, useThemedStyles } from '../theme/ThemeProvider';
import { subscribeUsersByUsernamePrefix, type UserSearchHit } from '../services/userSearch';
import { isFirebaseConfigured } from '../firebase/firebase';
import {
  getActiveMentionQuery,
  insertMentionAtCursor,
} from '../utils/commentMentions';
import type { ReplyTargetPayload } from './EngagementCommentRow';

type Props = {
  draft: string;
  onChangeText: (t: string) => void;
  replyTarget: ReplyTargetPayload | null;
  onClearReply: () => void;
  sending: boolean;
  onSend: () => void;
  forModal: boolean;
  reelLayout: boolean;
  onComposerFocus?: () => void;
  bottomInset?: number;
  /** Modal send reads draft from ref so Post works on first tap while keyboard is up. */
  draftTextRef?: React.MutableRefObject<string>;
  viewerUid?: string;
};

const MIN_INPUT_HEIGHT = 44;
const MAX_INPUT_HEIGHT = 128;
const MODAL_INPUT_HEIGHT = 44;
const MENTION_SUGGEST_LIMIT = 6;

function isAutoGeneratedUsername(raw: string): boolean {
  const u = String(raw ?? '')
    .trim()
    .replace(/^@+/u, '')
    .toLowerCase();
  if (!u) return true;
  if (u === 'user' || u === 'leaper' || u === 'u') return true;
  if (/^(user|leaper|u)_[a-z0-9_]+$/u.test(u)) return true;
  return false;
}

export const EngagementCommentComposer = React.memo(function EngagementCommentComposer({
  draft,
  onChangeText,
  replyTarget,
  onClearReply,
  sending,
  onSend,
  forModal,
  reelLayout,
  onComposerFocus,
  bottomInset = 0,
  draftTextRef,
  viewerUid,
}: Props) {
  const { colors } = useTheme();
  const styles = useThemedStyles((colors) => ({
    compose: {
      marginTop: 4,
      gap: 0,
    },
    composeRow: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      gap: 8,
    },
    composeReel: {
      marginTop: 0,
      paddingTop: 8,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
    },
    composeModal: {
      marginTop: 0,
      paddingTop: 8,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border2,
    },
    replyBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 8,
      paddingHorizontal: 10,
      marginBottom: 8,
      borderRadius: 12,
      backgroundColor: colors.cardTint,
      borderWidth: 1,
      borderColor: colors.border2,
    },
    replyBarTxt: {
      flex: 1,
      fontSize: 13,
      fontWeight: '700',
      color: colors.moss,
    },
    mentionPanel: {
      marginTop: 6,
      marginBottom: 6,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.card,
      maxHeight: 176,
      overflow: 'hidden',
      shadowColor: '#000',
      shadowOpacity: 0.08,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 6 },
      elevation: 12,
    },
    mentionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    mentionAvatar: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: colors.cardTint,
      alignItems: 'center',
      justifyContent: 'center',
    },
    mentionAvatarTxt: {
      fontSize: 12,
      fontWeight: '900',
      color: colors.text,
    },
    mentionUsername: {
      flex: 1,
      fontSize: 14,
      fontWeight: '800',
      color: colors.coral,
    },
    mentionLoading: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    mentionLoadingTxt: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.muted,
    },
    mentionEmpty: {
      paddingHorizontal: 12,
      paddingVertical: 10,
      fontSize: 13,
      fontWeight: '600',
      color: colors.muted,
    },
    input: {
      flex: 1,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 22,
      paddingHorizontal: 14,
      paddingTop: Platform.OS === 'ios' ? 10 : 8,
      paddingBottom: Platform.OS === 'ios' ? 10 : 8,
      fontSize: 15,
      fontWeight: '500',
      color: colors.text,
      backgroundColor: colors.bg,
      maxHeight: MAX_INPUT_HEIGHT,
    },
    inputModal: {
      backgroundColor: colors.cardTint,
      borderColor: colors.border2,
    },
    inputModalFixed: {
      height: MODAL_INPUT_HEIGHT,
      maxHeight: MODAL_INPUT_HEIGHT,
      paddingTop: Platform.OS === 'ios' ? 11 : 10,
      paddingBottom: Platform.OS === 'ios' ? 11 : 10,
    },
    sendBtn: {
      paddingHorizontal: 18,
      paddingVertical: 11,
      borderRadius: 22,
      backgroundColor: colors.moss,
      minWidth: 80,
      minHeight: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    sendBtnDisabled: {
      opacity: 0.45,
    },
    sendText: {
      color: colors.white,
      fontWeight: '900',
      fontSize: 14,
    },
  }));

  const inputRef = React.useRef<TextInput>(null);
  const [inputHeight, setInputHeight] = React.useState(MIN_INPUT_HEIGHT);
  const [selection, setSelection] = React.useState({ start: draft.length, end: draft.length });
  const [debouncedMentionQuery, setDebouncedMentionQuery] = React.useState('');
  const [mentionHits, setMentionHits] = React.useState<UserSearchHit[]>([]);
  const [mentionLoading, setMentionLoading] = React.useState(false);

  const activeMention = React.useMemo(
    () => getActiveMentionQuery(draft, selection.start),
    [draft, selection.start]
  );
  const mentionSearchPending = Boolean(
    activeMention && activeMention.query !== debouncedMentionQuery
  );
  const showMentionPanel = Boolean(activeMention && viewerUid && isFirebaseConfigured());

  React.useEffect(() => {
    if (!activeMention) {
      setDebouncedMentionQuery('');
      return;
    }
    const t = setTimeout(() => setDebouncedMentionQuery(activeMention.query), 220);
    return () => clearTimeout(t);
  }, [activeMention?.query, activeMention?.start]);

  React.useEffect(() => {
    if (!showMentionPanel || !viewerUid) {
      setMentionHits([]);
      setMentionLoading(false);
      return;
    }
    setMentionHits([]);
    setMentionLoading(true);
    const unsub = subscribeUsersByUsernamePrefix(
      debouncedMentionQuery,
      viewerUid,
      MENTION_SUGGEST_LIMIT,
      (hits) => {
        const sorted = [...hits].sort((a, b) => {
          const ar = isAutoGeneratedUsername(a.username) ? 1 : 0;
          const br = isAutoGeneratedUsername(b.username) ? 1 : 0;
          if (ar !== br) return ar - br;
          return a.username.localeCompare(b.username);
        });
        setMentionHits(sorted);
        setMentionLoading(false);
      }
    );
    return () => unsub();
  }, [showMentionPanel, viewerUid, debouncedMentionQuery]);

  React.useEffect(() => {
    if (forModal) return;
    if (!draft.trim()) setInputHeight(MIN_INPUT_HEIGHT);
  }, [draft, forModal]);

  React.useEffect(() => {
    if (!replyTarget) return;
    const t = setTimeout(() => {
      inputRef.current?.focus();
    }, 80);
    return () => clearTimeout(t);
  }, [replyTarget]);

  const currentDraft = forModal && draftTextRef ? draftTextRef.current : draft;
  const canSend = Boolean(currentDraft.trim()) && !sending;

  const handleSend = () => {
    const text = (forModal && draftTextRef ? draftTextRef.current : draft).trim();
    if (!text || sending) return;
    onSend();
  };

  const applyDraft = React.useCallback(
    (text: string, cursor: number) => {
      if (draftTextRef) draftTextRef.current = text;
      onChangeText(text);
      setSelection({ start: cursor, end: cursor });
      requestAnimationFrame(() => {
        inputRef.current?.setNativeProps({ selection: { start: cursor, end: cursor } });
      });
    },
    [draftTextRef, onChangeText]
  );

  const onSelectMention = React.useCallback(
    (hit: UserSearchHit) => {
      if (!activeMention) return;
      const next = insertMentionAtCursor({
        text: draft,
        mentionStart: activeMention.start,
        cursor: selection.start,
        username: hit.username,
      });
      applyDraft(next.text, next.cursor);
    },
    [activeMention, draft, selection.start, applyDraft]
  );

  const showMentionSpinner = showMentionPanel && (mentionSearchPending || mentionLoading);

  return (
    <View
      style={[
        styles.compose,
        reelLayout && !forModal && styles.composeReel,
        forModal && [styles.composeModal, { paddingBottom: bottomInset }],
      ]}
    >
      {replyTarget ? (
        <View style={styles.replyBar}>
          <Text style={styles.replyBarTxt} numberOfLines={1}>
            Replying to @{replyTarget.username}
          </Text>
          <TouchableOpacity onPress={onClearReply} hitSlop={10} accessibilityLabel="Cancel reply">
            <Ionicons name="close-circle" size={22} color={colors.muted} />
          </TouchableOpacity>
        </View>
      ) : null}
      {showMentionPanel ? (
        <View style={styles.mentionPanel}>
          {showMentionSpinner ? (
            <View style={styles.mentionLoading}>
              <ActivityIndicator size="small" color={colors.moss} />
              <Text style={styles.mentionLoadingTxt}>Finding users…</Text>
            </View>
          ) : mentionHits.length ? (
            <FlatList
              data={mentionHits}
              keyExtractor={(item) => item.uid}
              keyboardShouldPersistTaps="always"
              renderItem={({ item }) => (
                <TouchableOpacity
                  style={styles.mentionRow}
                  onPress={() => onSelectMention(item)}
                  accessibilityRole="button"
                  accessibilityLabel={`Mention ${item.username}`}
                >
                  <View style={styles.mentionAvatar}>
                    <Text style={styles.mentionAvatarTxt}>
                      {(item.username || '?').trim().slice(0, 1).toUpperCase()}
                    </Text>
                  </View>
                  <Text style={styles.mentionUsername}>@{item.username}</Text>
                </TouchableOpacity>
              )}
            />
          ) : (
            <Text style={styles.mentionEmpty}>No users match that handle.</Text>
          )}
        </View>
      ) : null}
      <View style={styles.composeRow}>
        <TextInput
          ref={inputRef}
          value={draft}
          onChangeText={(text) => {
            if (draftTextRef) draftTextRef.current = text;
            onChangeText(text);
          }}
          onSelectionChange={(e) => {
            const next = e.nativeEvent.selection;
            setSelection(next);
          }}
          placeholder={replyTarget ? `Reply to @${replyTarget.username}…` : 'Add a comment…'}
          placeholderTextColor={colors.muted}
          style={[
            styles.input,
            forModal ? styles.inputModal : null,
            forModal
              ? styles.inputModalFixed
              : { height: Math.max(MIN_INPUT_HEIGHT, inputHeight) },
          ]}
          editable={!sending}
          maxLength={500}
          multiline
          scrollEnabled={forModal || inputHeight >= MAX_INPUT_HEIGHT}
          textAlignVertical="top"
          onContentSizeChange={
            forModal
              ? undefined
              : (e) => {
                  const next = Math.min(
                    MAX_INPUT_HEIGHT,
                    Math.max(MIN_INPUT_HEIGHT, e.nativeEvent.contentSize.height + (Platform.OS === 'ios' ? 20 : 16))
                  );
                  setInputHeight((prev) => (Math.abs(prev - next) > 1 ? next : prev));
                }
          }
          onFocus={() => onComposerFocus?.()}
          blurOnSubmit={false}
          autoCorrect
          spellCheck
          textContentType="none"
          autoCapitalize="none"
        />
        {forModal ? (
          <Pressable
            style={[styles.sendBtn, !canSend && styles.sendBtnDisabled]}
            hitSlop={10}
            onPressIn={handleSend}
            accessibilityRole="button"
            accessibilityLabel="Post comment"
          >
            {sending ? (
              <ActivityIndicator color={colors.white} />
            ) : (
              <Text style={styles.sendText}>Post</Text>
            )}
          </Pressable>
        ) : (
          <TouchableOpacity
            style={[styles.sendBtn, !canSend && styles.sendBtnDisabled]}
            hitSlop={10}
            activeOpacity={0.88}
            onPress={handleSend}
            accessibilityRole="button"
            accessibilityLabel="Post comment"
          >
            {sending ? (
              <ActivityIndicator color={colors.white} />
            ) : (
              <Text style={styles.sendText}>Post</Text>
            )}
          </TouchableOpacity>
        )}
      </View>
    </View>
  );
});
