export const CONVERSATIONS = 'conversations';
export const CONVERSATION_MEMBERS = 'conversationMembers';
export const MESSAGES = 'messages';
export const MESSAGE_REACTIONS = 'messageReactions';
export const TYPING = 'typing';
export const USER_PRESENCE = 'userPresence';
export const USER_BLOCKS = 'userBlocks';
export const MESSAGE_REPORTS = 'messageReports';
/** Per-user chat list rows (classic inbox); doc id = conversation id. */
export const CHAT_CONVERSATIONS_INBOX = 'chatConversations';
